package project.witty.keys.keyboard.AiChat;

public enum AIFeatureType {
    AI_CHAT_WRITTEN, GRAMMAR, TRANSLATE_WRITTEN, GENERATE_READ_REPLY, TONALITY,
    AI_CHAT_READ, TRANSLATE_READ, LOOK_UP, SUMMARISE_READ, SIMPLIFY_READ,
    CROSS_VERIFY_READ, EXPLAIN_READ, REPHRASE_WRITTEN
}
